### ISSUE TITLE
iOS 10 requires Keychain Entitlements

### ISSUE THREAD

**Issue by dmorrow** [ideawu/Objective-C-RSA#27]
In order to properly encrypt a string with a public key, Keychain Entitlements must be enabled.

**Comment by ideawu** [comment]
Thanks, I have updated the README.md.

**Comment by startry** [comment]
What does "Keychain Entitlements must be enabled" meaning?

**Comment by ideawu** [comment]
@startry http://stackoverflow.com/a/38543243/427640
