### ISSUE TITLE
Would I need any license to use this code if I submit my Application to the AppStore?

### ISSUE THREAD

**Issue by harinsa** [ideawu/Objective-C-RSA#3]
As stated in the Developer Program License Agreement: 

> Section 2.3, You certify that (i) none of the Licensed Applications contains, uses or supports any data encryption or cryptographic functions; or (ii) in the event that any Licensed Application contains, uses or supports any such data encryption or cryptographic functionality, You certify that You have complied with the United States Export Administration Regulations, and are in possession of, and will, upon request, provide Apple with a PDF copy of Your Encryption Registration Number (ERN), or export classification ruling (CCATS) issued by the United States Commerce Department, Bureau of Industry and Security and PDF copies of appropriate authorizations from other countries that mandate import authorizations for that Licensed Application, as required.

https://developer.apple.com/programs/terms/ios/standard/ios_program_standard_agreement_20140909.pdf

Or even better, have any successfully submit their app to the store with this code?

**Comment by ideawu** [comment]
Hi, @harinsa , I have put a LICENSE file in the project, it is a New BSD License, which is widely used in many open source projects.

**Comment by harinsa** [comment]
@ideawu I mean things like ERN and CCATS. Is it required that I be registered with the US Commerce Department to get those documents to be able to use these codes in the AppStore?

**Comment by ideawu** [comment]
No, you don't need to register for this code, and you don't have to mention about this code in your app.

**Comment by harinsa** [comment]
Ok thanks
