### ISSUE TITLE
Android sample

### ISSUE THREAD

**Issue by MujasSam** [ideawu/Objective-C-RSA#44]
How to decrypt files/text in Android client?

**Comment by ideawu** [comment]
Sorry, I can't help, this project only works for Objective-C.

**Comment by MujasSam** [comment]
Looking into the PHP grep code for the default encryption method openssl_public_encrypt() equivalent in java will be "RSA/ECB/PKCS1PADDING" . This algorithm resolved the android issue. This will take care the PKCS#11 padding.

**Comment by MujasSam** [comment]
I Have solved the issue for Android and published the code in git in reply.

Best Regards,

Mujasam BN | Technical Lead - Mobility | Cell: +91 9986790097

*Dream**O**rbit **A Deloitte Technology Fast 50 Company*
<http://dreamorbit.com/deloitte-recognized-dreamorbit-among-top-500-emerging-technology-company-in-india/>
Upcoming Holiday : none  | Next Planned Leave : none
