### ISSUE TITLE
严重的bug

### ISSUE THREAD

**Issue by zengqingf** [ideawu/Objective-C-RSA#52]
字符串加密都没有问题，现在是我们有一个NSData类型的数据
数据格式是{0x97, 0x0, 0x10}
先用+ (NSData *)encryptData:(NSData *)data publicKey:(NSString *)pubKey加密
接着用+ (NSData *)decryptData:(NSData *)data privateKey:(NSString *)privKey解密
你会发现解密出来的数据只有1字节，也就是说代码中用0x0做了分隔符

**Comment by LionNeo** [comment]
在RSA.m 文件中找到+ (NSData *)decryptData:(NSData *)data withKeyRef:(SecKeyRef) keyRef;这个方法,然后注释这两行代码:
idxNextZero = i;
break;
即可解决
